/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
*******************************************************************************
 *				 _ _                                             _ _
				|   |                                           (_ _)
				|   |        _ _     _ _   _ _ _ _ _ _ _ _ _ _   _ _
				|   |       |   |   |   | |    _ _     _ _    | |   |
				|   |       |   |   |   | |   |   |   |   |   | |   |
				|   |       |   |   |   | |   |   |   |   |   | |   |
				|   |_ _ _  |   |_ _|   | |   |   |   |   |   | |   |
				|_ _ _ _ _| |_ _ _ _ _ _| |_ _|   |_ _|   |_ _| |_ _|
								(C)2022 Lumi
 * Copyright (c) 2022
 * Lumi, JSC.
 * All Rights Reserved
 *
 * File name: main.h
 *
 * Description:
 *
 *
 * Last Changed By:  $Author: dungpk $
 * Revision:         $Revision: $
 * Last Changed:     $Date: $June 1, 2022
 *
 * Code sample:
 ******************************************************************************/
/******************************************************************************/
/*                              INCLUDE FILES                                 */
/******************************************************************************/

#include <stdint.h>
#include <stdio.h>
#include "system_stm32f4xx.h"
#include "timer.h"
#include "eventman.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"
#include "uartcmd.h"
#include "serial.h"
#include "string.h"

/******************************************************************************/
/*                     PRIVATE TYPES and DEFINITIONS                         */
/******************************************************************************/
/******************************************************************************/
/*                     EXPORTED TYPES and DEFINITIONS                         */
/******************************************************************************/

// Dinh nghia thoi gian cap nhat nhiet do va do am
#define CYCLE_SEND_DATA 1000 //ms


// Khai bao kieu du lieu enum cho cac su kien
typedef enum {
	EVENT_EMPTY,
	EVENT_APP_INIT,
	EVENT_APP_FLUSHMEN_READY,
} even_api_t, *event_api_p;

// Khai bao dinh nghia enum cho cac trang thai
typedef enum {
	STATE_APP_STARTUP,
	STATE_APP_IDLE,
	STATE_APP_RESET,
} state_app_t;

typedef enum{
	LED_GREEN_DEFAULT,
	LED_GREEN_RAISE,
	LED_GREEN_FALL,
	LED_GREEN_NO_CHANGE,
}led_green_change_t;

typedef enum {
	LCD_DEFAULT = 0, 
	INFORMATION_KIT = 1,
	SENSOR_DISPLAY = 2;
}check_event_lcd_display_t;

typedef enum{
	BUTTON_0 = 0,
	BUTTON_1 = 1,
	BUTTON_2 = 2,
	BUTTON_3 = 3,
	BUTTON_4 = 4,
	BUTTON_5 = 5,
}button_t;

/******************************************************************************/
/*                              PRIVATE DATA                                  */
/******************************************************************************/

/******************************************************************************/
/*                              EXPORTED DATA                                 */
/******************************************************************************/

static state_app_t eCurrentState;// Khai bao bien luu trang thai hien tai dang hoat dong
static ucg_t ucg; // Khai bao bien kieu ucg_t su dung LCD
static _Bool g_boCheckLed = 0; // Khai bao Bien dieu khien tat bat led
static u8_t g_byLedLevelTemp[] = {0,100}; // Khai bao mang 2 phan tu luu gia tri de bat va tat led
static int8_t g_byLedGreenLevel = 0; // Khai bao bien luu gia tri do sang den GREEN
static led_green_change_t check_led_green = LED_GREEN_DEFAULT; // Khai bao bien dieu khien tang giam do sang cua den GREEN
static u32_t g_dwTimeCurrentSensor,g_dwTimeInitialSensor; // Khai bao bien thoi gian tinh thoi gian cho cap nhat nhiet do, do am,do sang
static u32_t g_dwTimeTotalSensor;// Khai bao bien luu tong thoi gian cho cap nhat tem,hum,g_wLightValue
static u32_t g_dwTimeCurrentLCD,g_dwTimeInitialLCD; // Khai bao bien cho thoi gian nghi de hien thi het duoc mo ta cua chip
static u32_t g_dwTimeTotalLCD = 0;//Bien luu tong thoi gian nghi de hien thi mo ta chip
static u32_t g_dwTimeCurrentChangLedGreen,g_dwTimeInitialChangLedGreen; // Bien luu thoi gian nghi khi dung tang giam led GREEN
static u32_t g_dwTimeTotalChangLedGreen = 0;// Bien luu gia tri cua thoi gian nghi cho den GREEN tat
static check_event_lcd_display_t check_lcd_display = LCD_DEFAULT; // Bien dieu khien thoi gian cho cho mo ta chip hien thi het len man hinh LCD
static u16_t g_wLightValue; // Bien luu gia tri do sang
static u8_t g_wTemperatureValue,g_wHumidityValue; // Bien luu gia tri nhiet do, do am
static i8_t g_ibLightString[20]= "";// cac chuoi luu gia tri cua nhiet do,do am,do sang
static i8_t g_ibTemperatureString[20]= "";
static i8_t g_ibg_wHumidityValueString[20]= "";

/******************************************************************************/
/*                            PRIVATE FUNCTIONS                               */
/******************************************************************************/

/******************************************************************************/
/*                            EXPORTED FUNCTIONS                              */
/******************************************************************************/


static void_t AppInitCommon(); // Ham khoi tao
static void_t AppStateManager(u8_t event);// Ham luu su kien
static void_t SetStateApp(state_app_t state); // Ham lay trang thai
static state_app_t GetStateApp(void_t); // Ham cap nhat trang thai dang su dung
static void_t LoadConfiguration (void_t); // Ham hien thi dau tien khi khoi dong
static void_t DeviceStateMachine(u8_t event); // Ham cap nhat cac hoat dong khi co nut nhan
static void_t change_led_green(void_t);// Ham thay doi do sang cua led GREEN
static void_t (*pcallbackData)() = change_led_green; // Ham con tro luu Ham chang_led_green de dua vao su kien Timerstart
static void_t Task_multiSensorScan (void_t); // Ham hien thi nhiet do, do am, do sang len LCD
static void_t MultiSensorScan(); // Ham cap nhat thoi gian thuc de cap nhat nhiet do, do am, do sang
static void_t LCD_Init(void_t);
static void_t LCD_Handlde(void_t);
static void_t LCD_DisplayDevice(void_t);
static void_t LedCmdSetState(u8_t byLed_ID,u8_t by_LedColor,u8_t byLedNumberBlink,u8_t byLedInterval, u8_t byLedLastState);
static void_t BuzzerCmdSetState(u8_t byBuzzerState); 
static void_t ButtonSetState(button_t button_id, uint8_t button_state);
static void_t LcdCmdSetState(char *str1);

/******************************************************************************/

int main(void_t)
{
	AppInitCommon(); // Khoi tao
	SetStateApp(STATE_APP_STARTUP);// trang thai dau tien
	EventSchedulerAdd(EVENT_APP_INIT);// Them su kien khoi tao vao queue
	TimerStart("eventtimer",50,255,pcallbackData,0); // Khoi tao timer xu ly trang khi muon thay doi led GREEN

	while(1)
	{
		processEventScheduler(); //xu ly su kien theo thoi gian dat truoc
		processTimerScheduler(); // xu ly su kien khi co nut nhan
		processSerialReceiver();
		LCD_Handlde();
	}

}


/**
 * @func   AppInitCommon
 * @brief  Initializes	Application
 * @param  None
 * @retval None
 */
void_t AppInitCommon(void_t)
{
	SystemCoreClockUpdate(); // cau hinh clock
	TimerInit();//Khoi tao timer xu ly su kien theo thoi gian
	EventSchedulerInit(AppStateManager);// Khoi tao bo dem luu danh sach su kien
	EventButton_Init();  // Cau hinh nut nhan
	BuzzerControl_Init(); // cau hinh coi
	LedControl_Init();// Cau hinh den led
	g_wLightValueSensor_Init(ADC_READ_MODE_DMA); //Cau hinh ADC che do hoat dong DMA
	TemHumSensor_Init();// Cau hinh ngoai vi ic2 voi cam bien nhiet do, do am
	LCD_Init();
	EventSerial_SetEventLedCallback(LedCmdSetState); 
	EventSerial_SetEventButtonCallback(ButtonSetState);  // Khởi tạo giao tiếp nút nhấn
	EventSerial_SetEventBuzzerCallback(BuzzerCmdSetState);  // Khởi tạo giao tiếp còi
	EventSerial_SetEventLcdCallback(LcdCmdSetState);  // Khởi tạo giao tiếp LCD

}

/**
 * @func   LCD_Handlde
 * @brief  Handle Event Display LCD
 * @param  None
 * @retval None
 */
static void_t LCD_Handlde(void_t){
			if(check_lcd_display == INFORMATION_KIT)
		{
			g_dwTimeCurrentLCD = GetMilSecTick();
			if(g_dwTimeCurrentLCD >= g_dwTimeInitialLCD)
				{
					g_dwTimeTotalLCD += g_dwTimeCurrentLCD - g_dwTimeInitialLCD;
				}
			else
				{
					g_dwTimeTotalLCD += 0xFFFFFFFFU - g_dwTimeCurrentLCD + g_dwTimeInitialLCD;
				}
			if(g_dwTimeTotalLCD >= 6000)
				{
					g_dwTimeTotalLCD = 0;
					ucg_ClearScreen(&ucg);
					check_lcd_display = SENSOR_DISPLAY;
					g_dwTimeInitialSensor = GetMilSecTick();
				}
			g_dwTimeInitialLCD = g_dwTimeCurrentLCD;
		}//Bat dau cap nhat nhiet do,do am, do sang
		if(check_lcd_display == SENSOR_DISPLAY)
		{
			MultiSensorScan();
		}

}

/**			
 * @func   LCD_Init
 * @brief  Initializes LCD
 * @param  None
 * @retval None
 */
static void_t LCD_Init(void_t)
{
		// Khoi tao LCD de cai dat font chu ,mau nen,mau chu,chieu hien thi
	Ucglib4WireSWSPI_begin(&ucg,UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);
	ucg_SetFont(&ucg,ucg_font_ncenR12_hr);
	ucg_SetColor(&ucg, 0, 255, 255, 255);
	ucg_SetColor(&ucg, 1, 0, 0, 0);
	ucg_SetRotate180(&ucg);
}

/**			
 * @func   AppStateManager
 * @brief  Handle Event
 * @param  event)
{
 * @retval None
 */
static void_t AppStateManager(u8_t event)
{
	switch(GetStateApp())
	{
		case STATE_APP_STARTUP:
			if (event == EVENT_APP_INIT)
			{
				SetStateApp(STATE_APP_IDLE);
			}
			LoadConfiguration();
			break;
		case STATE_APP_IDLE:
			DeviceStateMachine(event);
			break;
		case STATE_APP_RESET:
			break;
		default:
			break;
	}
}

/**			
 * @func   AppStateManager
 * @brief  Handle Event
 * @param  state
 * @retval None
 */
static void_t SetStateApp(state_app_t state)
{
	eCurrentState = state;
}

static state_app_t GetStateApp(void_t)
{
	return eCurrentState;
}

/**			
 * @func   LoadConfiguration
 * @brief  LoadConfiguration
 * @param  None
 * @retval None
 */
void_t LoadConfiguration (void_t)
{
	// Hien thi dong chu dau tien khi khoi dong
	ucg_ClearScreen(&ucg);
	ucg_DrawString(&ucg,46,20,0,"IOT ");
	ucg_DrawString(&ucg,10,45,0,"Programming");
	ucg_DrawString(&ucg,52,70,0,"by");
	ucg_DrawString(&ucg,42,95,0,"Lumi");
	ucg_DrawString(&ucg,20,120,0,"SmartHome");
}

/**			
 * @func   DeviceStateMachine
 * @brief  DeviceStateMachine
 * @param  event
 * @retval None
 */
void_t DeviceStateMachine(u8_t event)
{
	switch (event)
	{
		case EVENT_OF_BUTTON_3_PRESS_5_TIMES:
		{
			// Dieu khien Led khi nhan nut 3 5 lan
			LedControl_BlinkStart(LED_KIT_ID0,BLINK_GREEN,12,1000,LED_COLOR_BLACK);// Cho led nhay 5 lan
			// Cau hinh va hien thi thong tin thiet bi
			LCD_DisplayDevice();
		}

		break;

		case EVENT_OF_BUTTON_1_PRESS_LOGIC:
		{
			g_boCheckLed = !g_boCheckLed; // chuyen trang thai cua led khi nhan phim
			LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_RED,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SetMelody(pbeep);//Bat coi keu 1 tieng
			LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_RED,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SendPacketRespond(1);
		}
		break;
		case EVENT_OF_BUTTON_2_PRESS_LOGIC:
		{
			g_boCheckLed = !g_boCheckLed;// chuyen trang thai cua led khi nhan phim
			LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SetMelody(pbeep);//Bat coi keu 1 tieng
			LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SendPacketRespond(1);
			 break;
		}
		case EVENT_OF_BUTTON_5_PRESS_LOGIC:
		{
			g_boCheckLed = !g_boCheckLed;// chuyen trang thai cua led khi nhan phim
			LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_BLUE,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SetMelody(pbeep);//Bat coi keu 1 tieng
			LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_BLUE,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SendPacketRespond(1);
			 break;
		}
		case EVENT_OF_BUTTON_4_PRESS_LOGIC:
		{
			g_boCheckLed = !g_boCheckLed;// chuyen trang thai cua led khi nhan phim
			LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_WHITE,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SetMelody(pbeep);//Bat coi keu 1 tieng
			LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_WHITE,g_byLedLevelTemp[g_boCheckLed]);
			BuzzerControl_SendPacketRespond(1);
			 break;
		}
		case EVENT_OF_BUTTON_1_HOLD_1S:
		{
			check_led_green = LED_GREEN_RAISE; // cho bien = 1 de xu ly trong ham change_led_green
			break;
		}

		case EVENT_OF_BUTTON_5_HOLD_1S:
		{
			check_led_green = LED_GREEN_FALL;// cho bien = 2 de xu ly trong ham change_led_green
			break;
		}


		case EVENT_OF_BUTTON_1_RELEASED_1S:
		case EVENT_OF_BUTTON_5_RELEASED_1S:
		{
			check_led_green = LED_GREEN_NO_CHANGE;// cho bien = 3 de xu ly trong ham change_led_green
			g_dwTimeInitialChangLedGreen = GetMilSecTick(); // Khoi tao gia tri dau tien sau do 4s se tat led
			break;
		}

		default:
			check_led_green = LED_GREEN_NO_CHANGE;
			break;
	}
}

/**			
 * @func   LCD_DisplayDevice
 * @brief  Display Information Device
 * @param  None
 * @retval None
 */
static void_t LCD_DisplayDevice(void_t)
{
			ucg_ClearScreen(&ucg);
			ucg_SetFont(&ucg,ucg_font_ncenR08_hr);
			ucg_DrawString(&ucg,0,10,0,"Device:");
			ucg_DrawString(&ucg,0,22,0,"Board STM32 Nucleo");
			ucg_DrawString(&ucg,0,34,0,"Code:");
			ucg_DrawString(&ucg,0,46,0,"STM32F401RE_NUCLEO");
			ucg_DrawString(&ucg,0,58,0,"Manufacturer:");
			ucg_DrawString(&ucg,0,70,0,"STMicroelectronics");
			ucg_DrawString(&ucg,0,82,0,"Kit expansion:");
			ucg_DrawString(&ucg,0,94,0,"Lumi Smarthome");
			ucg_DrawString(&ucg,0,106,0,"Project:");
			ucg_DrawString(&ucg,0,118,0,"Simulator touch switch");
			check_lcd_display = INFORMATION_KIT; // cho phep bo dem thoi gian bat dau chay de hien thi het thong tin thiet bi
			g_dwTimeInitialLCD = GetMilSecTick();// luu thoi gian dau tien de bat dau tinh thoi gian
}

/**			
 * @func   Change_led_green
 * @brief  Handle Raise and Reduce Led Green
 * @param  None
 * @retval None
 */
void_t change_led_green(void_t)
{
	if(check_led_green == LED_GREEN_RAISE) // xet truong hop tang led
	{
		g_byLedGreenLevel += 1; // Tang gia tri cua bien them 1 moi 20ms
		if(g_byLedGreenLevel >=100) // Neu bien lon hon 100 se bang 100
		{
			g_byLedGreenLevel = 100;
		}
		LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedGreenLevel);//Hien thi do sang led
	}
	if(check_led_green == LED_GREEN_FALL) // xet truong hop giam led
	{
		g_byLedGreenLevel -= 1;  // giam gia tri cua bien di 1 moi 20ms
		if(g_byLedGreenLevel <= 0) // Neu bien gia tri nho hon 0 se bang 0
		{
			g_byLedGreenLevel = 0;
		}
		LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedGreenLevel);// Hien thi led theo do sang
	}

	if(check_led_green == LED_GREEN_FALL_NO_CHANGE)
	{
		g_dwTimeCurrentChangLedGreen = GetMilSecTick(); // Khoi tao gia tri thoi gian hien tai so sanh voi thoi gian khoi tao
		if(g_dwTimeCurrentChangLedGreen >= g_dwTimeInitialChangLedGreen)
		{
			g_dwTimeTotalChangLedGreen += g_dwTimeCurrentChangLedGreen - g_dwTimeInitialChangLedGreen;
		}
		else
		{
			g_dwTimeTotalChangLedGreen += 0xFFFFFFFFU - g_dwTimeCurrentChangLedGreen + g_dwTimeInitialChangLedGreen;
		}
		if(g_dwTimeTotalChangLedGreen >= 4000) // Sau 4s den se tu tat
		{
			g_dwTimeTotalChangLedGreen = 0;
			check_led_green = 0;
			LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_GREEN,0);

		}
		g_dwTimeInitialChangLedGreen = g_dwTimeCurrentChangLedGreen;

	}
	else
	{

	}
}

/**			
 * @func   Task_multiSensorScan
 * @brief  Update Sensor Value
 * @param  None
 * @retval None
 */
void_t  Task_multiSensorScan (void_t) // Hien thi do sang, do am, nhiet do len LCD
{
	g_wLightValue = g_wLightValueSensor_MeasureUseDMAMode();
	g_wTemperatureValue = (u8_t)(TemHumSensor_GetTemp()/100);
	g_wHumidityValue = (u8_t)(TemHumSensor_GetHumi()/100);
	ucg_SetFont(&ucg,ucg_font_ncenR12_hr);
	memset(g_ibTemperatureString,0,sizeof(g_ibTemperatureString));
	memset(g_ibg_wHumidityValueString,0,sizeof(g_ibg_wHumidityValueString));
	memset(g_ibLightString,0,sizeof(g_ibLightString));
	ucg_DrawString(&ucg,0,32,0,g_ibTemperatureString);
	sprintf(g_ibg_wHumidityValueString,"Humi = %02d %%",g_wHumidityValue); // Hien thi do am len LCD
	ucg_DrawString(&ucg,0,52,0,g_ibg_wHumidityValueString);
	sprintf(g_ibTemperatureString,"Temp = %02d oC",g_wTemperatureValue);// Hien thi nhiet do
	ucg_DrawString(&ucg,0,72,0,g_ibLightString);
	sprintf(g_ibLightString,"g_wLightValue = %04d lux",g_wLightValue);// Hien thi do sang
	TempSensor_SendPacketRespond(g_wTemperatureValue);
	HumiSensor_SendPacketRespond(g_ibg_wHumidityValueString);
	LightSensor_SendPacketRespond(g_wLightValue);
}

/**			
 * @func   MultiSensorScan
 * @brief  Display Sensor Value
 * @param  None
 * @retval None
 */
void_t MultiSensorScan() //  cap nhat thoi gian de hiển thị lên LCD
{
	g_dwTimeCurrentSensor = GetMilSecTick();
		if(g_dwTimeCurrentSensor >= g_dwTimeInitialSensor)
			{
				g_dwTimeTotalSensor += g_dwTimeCurrentSensor - g_dwTimeInitialSensor;
			}
		else
			{
				g_dwTimeTotalSensor += 0xFFFFFFFFU - g_dwTimeCurrentSensor + g_dwTimeInitialSensor;
			}
		if(g_dwTimeTotalSensor >= CYCLE_SEND_DATA)
			{
				g_dwTimeTotalSensor = 0;
				Task_multiSensorScan();
			}
		g_dwTimeInitialSensor = g_dwTimeCurrentSensor;
}

/**			
 * @func   LedCmdSetState
 * @brief  Process Led Message Received From Simulation
 * @param  byLed_ID,by_LedColor,byLedNumberBlink,byLedInterval,byLedLastState
 * @retval None
 */
static void_t LedCmdSetState(u8_t byLed_ID,u8_t by_LedColor,u8_t byLedNumberBlink,u8_t byLedInterval, u8_t byLedLastState)
{
	LedControl_BlinkStart(byLed_ID,by_LedColor, byLedNumberBlink, byLedInterval, byLedLastState);
};


/**			
 * @func   BuzzerCmdSetState
 * @brief  Process Buzzer Message Received From Simulation
 * @param  byBuzzerState
 * @retval None
 */
static void_t BuzzerCmdSetState(uint8_t byBuzzerState){
		uint8_t i = 0;
	for (i=0;i< byBuzzerState;i++)
	{
		BuzzerControl_SetMelody(pbeep);
	}
}


/**			
 * @func   LcdCmdSetState
 * @brief  Process LCD Message Received From Simulation
 * @param  str
 * @retval None
 */
static void_t LcdCmdSetState(char *str1)
{
	ucg_ClearScreen(&ucg);
	ucg_SetFont(&ucg,ucg_font_ncenR08_hr);
	ucg_DrawString(&ucg,0,10,0,str1);
	check_time = 1;
	time_initial1 = GetMilSecTick();
}

/**			
 * @func   ButtonSetState
 * @brief  Process Button Message Received From Simulation
 * @param  button_id,button_state
 * @retval None
 */
static void_t ButtonSetState(button_t button_id, uint8_t button_state)  // tuong tu ham DeviceStateMachine
{
	switch (button_id) // button_id được lấy giá trị từ  hàm
		{
			case BUTTON_1:
			{
				g_boCheckLed = !g_boCheckLed;
				LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_RED,g_byLedLevelTemp[g_boCheckLed]);
				LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_RED,g_byLedLevelTemp[g_boCheckLed]);
				BuzzerControl_SetMelody(pbeep);
				BuzzerControl_SendPacketRespond(1);
			}
			break;
			case BUTTON_2:
			{
				g_boCheckLed = !g_boCheckLed;
				LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedLevelTemp[g_boCheckLed]);
				LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_GREEN,g_byLedLevelTemp[g_boCheckLed]);
				BuzzerControl_SetMelody(pbeep);
				BuzzerControl_SendPacketRespond(1);
				 break;
			}
			case BUTTON_5:
			{
				g_boCheckLed = !g_boCheckLed;
				LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_BLUE,g_byLedLevelTemp[g_boCheckLed]);
				LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_BLUE,g_byLedLevelTemp[g_boCheckLed]);
				 BuzzerControl_SetMelody(pbeep);
				 BuzzerControl_SendPacketRespond(1);
				 break;
			}
			case BUTTON_4:
			{
				g_boCheckLed = !g_boCheckLed;
				LedControl_SetColorGeneral(LED_KIT_ID0,LED_COLOR_WHITE,g_byLedLevelTemp[g_boCheckLed]);
				LedControl_SendPacketRespond(LED_KIT_ID0,LED_COLOR_WHITE,g_byLedLevelTemp[g_boCheckLed]);
				BuzzerControl_SetMelody(pbeep);
				BuzzerControl_SendPacketRespond(1);
				 break;
			}

			default:

				break;
		}

}
